Repository Sobek-W-A/edt-manager-backend, pull requests merged in 2025-01, with the labels that each got.

#62 61 refactor before sprint start
  app/main.py
  app/models/pydantic/AccountMetadataModel.py
  app/models/pydantic/AccountModel.py
  app/models/pydantic/CoefficientModel.py
  app/models/pydantic/CourseModel.py
  app/models/pydantic/CourseTypeModel.py
  app/models/pydantic/FolderModel.py
  app/models/pydantic/NodeModel.py
  app/models/pydantic/OperationModel.py
  app/models/pydantic/PermissionsModel.py
  app/models/pydantic/ProfileModel.py
  app/models/pydantic/PydanticRole.py
  app/models/pydantic/RoleModel.py
  app/models/pydantic/ServiceModel.py
  app/models/pydantic/StatusModel.py
  app/models/pydantic/UEModel.py
  app/models/pydantic/abstract/AcademicYearModel.py
  app/models/pydantic/abstract/ClassicModel.py
  app/models/pydantic/tools/model_converter.py
  app/models/pydantic/tools/validator.py
  app/models/tortoise/permission.py
  app/routes/account.py
  app/routes/auth.py
  app/routes/course.py
  app/routes/course_type.py
  app/routes/role.py
  app/routes/status.py
  app/routes/statut.py
  app/routes/ue.py
  app/services/AccountService.py
  app/services/PermissionService.py
  app/services/RoleService.py
  app/services/StatusService.py
  app/services/UEService.py
  app/static/templates/json/account_metadata_templates.json
  app/static/templates/json/course_type_templates.json
  app/static/templates/json/operation_templates.json
  app/static/templates/json/permission_templates.json
  app/static/templates/json/role_templates.json
  app/static/templates/json/service_templates.json
  app/static/templates/json/status_templates.json
  app/utils/databases/datasets.py
  app/utils/databases/db.py
  app/utils/enums/colors.py
  app/utils/enums/courses_enums.py
  app/utils/enums/enum_loaders.py
  app/utils/enums/permission_enums.py
  app/utils/printers.py
Labels: enhancement, Priority

#65 56 addpagination for large queries
  app/models/pydantic/tools/pagination.py
Labels: enhancement

#75 Fixing account search
  app/models/tortoise/account.py
  app/models/tortoise/profile.py
  app/routes/account.py
  app/services/AccountService.py
  app/services/ProfileService.py
Labels: bug, enhancement

#78 Fixed the issue.
  app/models/pydantic/UEModel.py
  app/models/tortoise/ue.py
  app/static/templates/json/ue_templates.json
Labels: bug, Priority

#76 74 ajout d'un patch pour les affectations
  app/models/pydantic/AffectationModel.py
  app/models/tortoise/affectation.py
  app/routes/affectation.py
  app/services/AffectationService.py
Labels: enhancement

#79 64 crud uecourse
  app/models/pydantic/CourseModel.py
  app/models/pydantic/CourseTypeModel.py
  app/models/pydantic/UEModel.py
  app/models/tortoise/course.py
  app/models/tortoise/course_type.py
  app/models/tortoise/ue.py
  app/routes/course.py
  app/routes/ue.py
  app/services/CourseService.py
  app/services/UEService.py
  app/utils/enums/http_errors.py
Labels: Priority

#81 Fixed the issue.
  app/routes/profile.py
Labels: bug, Priority

#85 83 ajout dune route retournant les comptes non associés à des profils
  app/models/pydantic/AccountModel.py
  app/models/pydantic/ProfileModel.py
  app/models/tortoise/profile.py
  app/routes/account.py
  app/routes/profile.py
  app/routes/status.py
  app/services/AccountService.py
  app/services/ProfileService.py
  app/utils/enums/http_errors.py
Labels: bug, enhancement, Priority

#91 Fixed the issue. Also added the profile in the response object for affectations.
  app/models/pydantic/AffectationModel.py
  app/routes/affectation.py
  app/services/AffectationService.py
Labels: Priority

#97 73 crud nodes pour larborescence
  app/main.py
  app/models/pydantic/NodeModel.py
  app/models/tortoise/node.py
  app/models/tortoise/ue.py
  app/routes/node.py
  app/services/CourseService.py
  app/services/NodeService.py
  app/static/templates/json/node_templates.json
  app/utils/enums/http_errors.py
  app/utils/enums/permission_enums.py
Labels: enhancement
